### PR TITLE
Added server configuration to repo

### LINKED ISSUE #61: We should keep a copy of the server configuration we use for this research
This makes it easy to refer to in our thesises

### PR DESCRIPTION
**Pull request by DanielPerezJensen**
We can then cite the server configuration we used more easily in our
thesis.

Closes #61

### CODE REVIEW

**Comment by dorian4840** [comment]
So just add the server configurations and simulations we use to this folder?

**Comment by DanielPerezJensen** [comment]
For now I have listed the sample config, and the custom config is talked about in the README.md. What configs do you want to add?

**Comment by dorian4840** [comment]
I have a custom config that I used for evaluation my exploration algorithms. Should I add these files, or is this meant to simply show how we created the custom configs?

**Comment by DanielPerezJensen** [comment]
You can add those, please also amend the README in the folder.

**Pull request merged**
